// @vitest-environment node

import { describe, expect, it } from 'vitest';

import { createJsonExport, computeJsonExportChecksum } from '../../src/lib/export';
import { parseImportPayload } from '../../src/services/importValidation';
import { OPSNORMAL_APP_NAME, type JsonExportPayload } from '../../src/types';

function buildPayload(overrides: Partial<JsonExportPayload> = {}): JsonExportPayload {
  return {
    app: OPSNORMAL_APP_NAME,
    schemaVersion: 1,
    exportedAt: '2026-03-28T12:00:00.000Z',
    entries: [
      {
        id: 1,
        date: '2026-03-28',
        sectorId: 'body',
        status: 'nominal',
        updatedAt: '2026-03-28T12:00:00.000Z'
      }
    ],
    ...overrides
  };
}

describe('shared import validation', () => {
  it('rejects invalid JSON', async () => {
    await expect(parseImportPayload('{')).rejects.toThrow('Import rejected. File is not valid JSON.');
  });

  it('rejects a payload missing required fields', async () => {
    await expect(parseImportPayload(JSON.stringify({ entries: [] }))).rejects.toThrow(
      'app - Invalid literal value, expected "OpsNormal"'
    );
  });

  it('rejects blocked keys before schema validation', async () => {
    const raw = '{"app":"OpsNormal","schemaVersion":1,"exportedAt":"2026-03-28T12:00:00.000Z","entries":[],"__proto__":{}}';

    await expect(parseImportPayload(raw)).rejects.toThrow(
      'Import rejected. File contains blocked keys.'
    );
  });

  it('rejects nested blocked keys before schema validation', async () => {
    const raw = '{"app":"OpsNormal","schemaVersion":1,"exportedAt":"2026-03-28T12:00:00.000Z","entries":[],"metadata":{"constructor":{}}}';

    await expect(parseImportPayload(raw)).rejects.toThrow(
      'Import rejected. File contains blocked keys.'
    );
  });

  it('rejects invalid sectors', async () => {
    const raw = JSON.stringify(
      buildPayload({
        entries: [
          {
            id: 1,
            date: '2026-03-28',
            sectorId: 'invalid-sector' as never,
            status: 'nominal',
            updatedAt: '2026-03-28T12:00:00.000Z'
          }
        ]
      })
    );

    await expect(parseImportPayload(raw)).rejects.toThrow();
  });

  it('rejects a payload with an invalid checksum format', async () => {
    const payload = buildPayload({
      checksum: 'abc123'
    });

    await expect(parseImportPayload(JSON.stringify(payload))).rejects.toThrow(
      'checksum - Checksum must be a 64-character lowercase SHA-256 hex digest.'
    );
  });

  it('accepts a payload with a valid checksum', async () => {
    const payload = buildPayload();
    payload.checksum = await computeJsonExportChecksum({
      app: payload.app,
      schemaVersion: payload.schemaVersion,
      exportedAt: payload.exportedAt,
      entries: payload.entries
    });

    const parsed = await parseImportPayload(JSON.stringify(payload));

    expect(parsed.checksum).toBe(payload.checksum);
  });

  it('accepts a real export generated by createJsonExport', async () => {
    const raw = await createJsonExport(
      [
        {
          id: 1,
          date: '2026-03-28',
          sectorId: 'body',
          status: 'nominal',
          updatedAt: '2026-03-28T12:00:00.000Z'
        }
      ],
      '2026-03-28T12:00:00.000Z'
    );

    const parsed = await parseImportPayload(raw);

    expect(parsed.entries).toHaveLength(1);
    expect(parsed.entries[0]?.sectorId).toBe('body');
    expect(parsed.checksum).toMatch(/^[a-f0-9]{64}$/);
  });

  it('rejects a payload with a mismatched checksum', async () => {
    const payload = buildPayload();
    payload.checksum = await computeJsonExportChecksum({
      app: payload.app,
      schemaVersion: payload.schemaVersion,
      exportedAt: payload.exportedAt,
      entries: payload.entries
    });
    payload.entries[0] = {
      ...payload.entries[0]!,
      status: 'degraded'
    };

    await expect(parseImportPayload(JSON.stringify(payload))).rejects.toThrow(
      'Import rejected. File integrity check failed. The backup may be corrupted or modified.'
    );
  });


  it('accepts a payload with optional crash diagnostics', async () => {
    const payload = buildPayload({
      crashDiagnostics: {
        connectionDropsDetected: 1,
        reconnectSuccesses: 1,
        reconnectFailures: 0,
        reconnectState: 'steady',
        lastReconnectError: null,
        persistAttempted: true,
        persistGranted: false,
        standaloneMode: false,
        installRecommended: true,
        webKitRisk: true,
        lastVerificationResult: 'verified',
        lastVerifiedAt: '2026-03-28T12:00:00.000Z'
      }
    });
    payload.checksum = await computeJsonExportChecksum({
      app: payload.app,
      schemaVersion: payload.schemaVersion,
      exportedAt: payload.exportedAt,
      entries: payload.entries,
      crashDiagnostics: payload.crashDiagnostics
    });

    const parsed = await parseImportPayload(JSON.stringify(payload));

    expect(parsed.crashDiagnostics?.connectionDropsDetected).toBe(1);
    expect(parsed.checksum).toBe(payload.checksum);
  });

  it('rejects a payload when crash diagnostics are modified after checksum generation', async () => {
    const payload = buildPayload({
      crashDiagnostics: {
        connectionDropsDetected: 1,
        reconnectSuccesses: 1,
        reconnectFailures: 0,
        reconnectState: 'steady',
        lastReconnectError: null,
        persistAttempted: true,
        persistGranted: false,
        standaloneMode: false,
        installRecommended: true,
        webKitRisk: true,
        lastVerificationResult: 'verified',
        lastVerifiedAt: '2026-03-28T12:00:00.000Z'
      }
    });

    payload.checksum = await computeJsonExportChecksum({
      app: payload.app,
      schemaVersion: payload.schemaVersion,
      exportedAt: payload.exportedAt,
      entries: payload.entries,
      crashDiagnostics: payload.crashDiagnostics
    });

    payload.crashDiagnostics = {
      ...payload.crashDiagnostics!,
      reconnectFailures: 1
    };

    await expect(parseImportPayload(JSON.stringify(payload))).rejects.toThrow(
      'Import rejected. File integrity check failed. The backup may be corrupted or modified.'
    );
  });

  it('accepts legacy payloads without a checksum', async () => {
    const legacyPayload = buildPayload();
    delete legacyPayload.checksum;
    const parsed = await parseImportPayload(JSON.stringify(legacyPayload));

    expect(parsed.entries).toHaveLength(1);
    expect(parsed.checksum).toBeUndefined();
  });
});
