// @vitest-environment node

import { describe, expect, it } from 'vitest';

import {
  CHECKSUM_ALGORITHM_V2,
  createJsonExport,
  computeJsonExportChecksum,
} from '../../src/lib/export';
import {
  createRejectedImportPreview,
  getSuccessfulImportPreviewKind,
  parseImportPayload,
} from '../../src/services/importValidation';
import { OPSNORMAL_APP_NAME, type JsonExportPayload } from '../../src/types';

function buildPayload(
  overrides: Partial<JsonExportPayload> = {},
): JsonExportPayload {
  return {
    app: OPSNORMAL_APP_NAME,
    schemaVersion: 1,
    exportedAt: '2026-03-28T12:00:00.000Z',
    entries: [
      {
        id: 1,
        date: '2026-03-28',
        sectorId: 'body',
        status: 'nominal',
        updatedAt: '2026-03-28T12:00:00.000Z',
      },
    ],
    ...overrides,
  };
}

async function captureRejection(promise: Promise<unknown>): Promise<unknown> {
  try {
    await promise;
  } catch (error: unknown) {
    return error;
  }

  throw new Error('Expected promise to reject.');
}

describe('shared import validation', () => {
  it('rejects invalid JSON', async () => {
    await expect(parseImportPayload('{')).rejects.toThrow(
      'Import rejected. File is not valid JSON.',
    );
  });

  it('rejects a payload missing required fields', async () => {
    await expect(
      parseImportPayload(JSON.stringify({ entries: [] })),
    ).rejects.toThrow('app - Invalid literal value, expected "OpsNormal"');
  });

  it('rejects blocked keys before schema validation', async () => {
    const raw =
      '{"app":"OpsNormal","schemaVersion":1,"exportedAt":"2026-03-28T12:00:00.000Z","entries":[],"__proto__":{}}';

    await expect(parseImportPayload(raw)).rejects.toThrow(
      'Import rejected. File contains blocked key "__proto__".',
    );
  });

  it('rejects nested blocked keys before schema validation', async () => {
    const raw =
      '{"app":"OpsNormal","schemaVersion":1,"exportedAt":"2026-03-28T12:00:00.000Z","entries":[],"metadata":{"constructor":{}}}';

    await expect(parseImportPayload(raw)).rejects.toThrow(
      'Import rejected. File contains blocked key "constructor".',
    );
  });

  it('rejects incompatible schema versions before write', async () => {
    await expect(
      parseImportPayload(
        JSON.stringify({
          ...buildPayload(),
          schemaVersion: 2,
        }),
      ),
    ).rejects.toThrow(
      'Import rejected. Backup schema version is incompatible with this build.',
    );
  });

  it('rejects invalid sectors', async () => {
    const raw = JSON.stringify(
      buildPayload({
        entries: [
          {
            id: 1,
            date: '2026-03-28',
            sectorId: 'invalid-sector' as never,
            status: 'nominal',
            updatedAt: '2026-03-28T12:00:00.000Z',
          },
        ],
      }),
    );

    await expect(parseImportPayload(raw)).rejects.toThrow();
  });

  it('rejects a payload with an invalid checksum format', async () => {
    const payload = buildPayload({
      checksum: 'abc123',
    });

    await expect(parseImportPayload(JSON.stringify(payload))).rejects.toThrow(
      'checksum - Checksum must be a 64-character lowercase SHA-256 hex digest.',
    );
  });

  it('accepts a payload with a valid checksum', async () => {
    const payload = buildPayload();
    const checksum: string = await computeJsonExportChecksum({
      app: payload.app,
      schemaVersion: payload.schemaVersion,
      exportedAt: payload.exportedAt,
      entries: payload.entries,
    });
    payload.checksum = checksum;

    const parsed = await parseImportPayload(JSON.stringify(payload));

    expect(parsed.checksum).toBe(payload.checksum);
  });

  it('accepts a real export generated by createJsonExport', async () => {
    const raw = await createJsonExport(
      [
        {
          id: 1,
          date: '2026-03-28',
          sectorId: 'body',
          status: 'nominal',
          updatedAt: '2026-03-28T12:00:00.000Z',
        },
      ],
      '2026-03-28T12:00:00.000Z',
    );

    const parsed = await parseImportPayload(raw);

    expect(parsed.entries).toHaveLength(1);
    expect(parsed.entries[0]?.sectorId).toBe('body');
    expect(parsed.checksumAlgorithm).toBe(CHECKSUM_ALGORITHM_V2);
    expect(parsed.checksum).toMatch(/^[a-f0-9]{64}$/);
  });

  it('rejects unknown checksum algorithms as incompatible', async () => {
    const error = await captureRejection(
      parseImportPayload(
        JSON.stringify({
          ...buildPayload(),
          checksumAlgorithm: 'sha256-canonical-v9',
        }),
      ),
    );

    expect(createRejectedImportPreview(error)).toEqual({
      kind: 'incompatible',
      reason: 'algorithm',
      detectedAppName: 'OpsNormal',
      detectedSchemaVersion: 1,
    });
  });

  it('rejects a payload with a mismatched checksum', async () => {
    const payload = buildPayload();
    const checksum: string = await computeJsonExportChecksum({
      app: payload.app,
      schemaVersion: payload.schemaVersion,
      exportedAt: payload.exportedAt,
      entries: payload.entries,
    });
    payload.checksum = checksum;
    payload.entries[0] = {
      ...payload.entries[0]!,
      status: 'degraded',
    };

    await expect(parseImportPayload(JSON.stringify(payload))).rejects.toThrow(
      'Import rejected. File integrity check failed. The backup may be corrupted or modified.',
    );
  });

  it('classifies stale verified backups as risky preview candidates', () => {
    const kind = getSuccessfulImportPreviewKind({
      ...buildPayload({
        checksum: 'a'.repeat(64),
        exportedAt: '2026-03-20T12:00:00.000Z',
      }),
    });

    expect(kind).toBe('stale');
  });

  it('serializes incompatible and checksum-failed paths into read-only preview states', async () => {
    const checksumPayload = buildPayload();
    checksumPayload.checksum = await computeJsonExportChecksum({
      app: checksumPayload.app,
      schemaVersion: checksumPayload.schemaVersion,
      exportedAt: checksumPayload.exportedAt,
      entries: checksumPayload.entries,
    });
    checksumPayload.entries[0] = {
      ...checksumPayload.entries[0]!,
      status: 'degraded',
    };

    const incompatibleError = await captureRejection(
      parseImportPayload(
        JSON.stringify({
          ...buildPayload(),
          schemaVersion: 2,
        }),
      ),
    );
    const checksumError = await captureRejection(
      parseImportPayload(JSON.stringify(checksumPayload)),
    );

    expect(createRejectedImportPreview(incompatibleError)).toEqual({
      kind: 'incompatible',
      reason: 'schema-version',
      detectedAppName: 'OpsNormal',
      detectedSchemaVersion: 2,
    });
    expect(createRejectedImportPreview(checksumError)).toEqual({
      kind: 'checksum-failed',
    });
  });

  it('accepts a payload with optional crash diagnostics', async () => {
    const payload = buildPayload({
      crashDiagnostics: {
        connectionDropsDetected: 1,
        reconnectSuccesses: 1,
        reconnectFailures: 0,
        reconnectState: 'steady',
        lastReconnectError: null,
        persistAttempted: true,
        persistGranted: false,
        standaloneMode: false,
        installRecommended: true,
        webKitRisk: true,
        lastVerificationResult: 'verified',
        lastVerifiedAt: '2026-03-28T12:00:00.000Z',
      },
    });
    payload.checksum = await computeJsonExportChecksum({
      app: payload.app,
      schemaVersion: payload.schemaVersion,
      exportedAt: payload.exportedAt,
      entries: payload.entries,
      crashDiagnostics: payload.crashDiagnostics,
    });

    const parsed = await parseImportPayload(JSON.stringify(payload));

    expect(parsed.crashDiagnostics?.connectionDropsDetected).toBe(1);
    expect(parsed.checksum).toBe(payload.checksum);
  });

  it('rejects a payload when crash diagnostics are modified after checksum generation', async () => {
    const payload = buildPayload({
      crashDiagnostics: {
        connectionDropsDetected: 1,
        reconnectSuccesses: 1,
        reconnectFailures: 0,
        reconnectState: 'steady',
        lastReconnectError: null,
        persistAttempted: true,
        persistGranted: false,
        standaloneMode: false,
        installRecommended: true,
        webKitRisk: true,
        lastVerificationResult: 'verified',
        lastVerifiedAt: '2026-03-28T12:00:00.000Z',
      },
    });

    payload.checksum = await computeJsonExportChecksum({
      app: payload.app,
      schemaVersion: payload.schemaVersion,
      exportedAt: payload.exportedAt,
      entries: payload.entries,
      crashDiagnostics: payload.crashDiagnostics,
    });

    payload.crashDiagnostics = {
      ...payload.crashDiagnostics!,
      reconnectFailures: 1,
    };

    await expect(parseImportPayload(JSON.stringify(payload))).rejects.toThrow(
      'Import rejected. File integrity check failed. The backup may be corrupted or modified.',
    );
  });

  it('accepts legacy payloads without a checksum', async () => {
    const legacyPayload = buildPayload();
    delete legacyPayload.checksum;
    const parsed = await parseImportPayload(JSON.stringify(legacyPayload));

    expect(parsed.entries).toHaveLength(1);
    expect(parsed.checksum).toBeUndefined();
  });
});
